nginx:
   image: nginx:latest
   ports:
      - 80:80
   #  - 5043:443
   links:
     - private_registry:registry_auth
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/registry.conf:/etc/nginx/conf.d/registry.conf:ro
     - ./nginx/registry.passwd:/etc/nginx/.htpasswd:ro
     - ./logs:/var/log/nginx:rw
   restart: always

private_registry:
    image: registry:2.5
    ports:
      - 5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./registry_v2_data:/var/lib/registry
    restart: always

