version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 5000:80
    depends_on:
      - registry_auth
    links:
      - registry_auth:registry_auth
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/registry.conf:/etc/nginx/conf.d/registry.conf:ro
      - ./nginx/registry.passwd:/etc/nginx/.htpasswd:ro
    restart: always
    network_mode: "bridge"

  registry_auth:
    container_name: registry
    image: registry:2.6.2
    restart: always
    ports:
      - 127.0.0.1:5001:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./data:/var/lib/registry
    links:
      - cache:redis
    network_mode: "bridge"

  cache:
     container_name: redis
     image: "redis:latest"
     ports:
       - 127.0.0.1:6379:6379
     restart: always
     command: "--maxmemory 16mb --maxmemory-policy allkeys-lru"
     network_mode: "bridge"

